version: '3'

services:

  web:
    image: gorillajs/python
    ports:  
      - "{{docker.port}}:80"
    volumes:
      - ../template:/root/templates
      - ../../src:/var/www/{{project.domain}}
      - ../../logs:/var/log/django
    container_name: {{project.domain}}
    entrypoint:
      - bin/sh
      - /root/templates/entrypoint-web.sh

networks:
  default:
    external:
      name: gorillajs

