version: '3'

services:

  web:
    image: gorillajs/apache-base
    volumes:
      - ../{{docker.templatefolder}}:/root/templates
      - ../../src:/var/www/{{project.domain}}/src
    container_name: {{project.domain}}

networks:
  default:
    external:
      name: gorillajs

