version: '3'

services:

  web:
    image: gorillajs/nodejs
    ports:  
      - "{{docker.port}}:80"
    volumes:
      - ../template:/root/templates
      - ../../.:/var/www/{{project.domain}}
    entrypoint:
      - bin/sh
      - /root/templates/entrypoint-web.sh
    container_name: {{project.domain}}

networks:
  default:
    external:
      name: gorillajs

