# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/mongo . -f templates/common/dockerfile-mongo

FROM ubuntu:14.04

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 \
    && echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list \
    && apt-get update && apt-get -y install mongodb-org supervisor && apt-get autoremove

COPY templates/common/mongo-supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
