version: '3'

services:

  mysql:
    image: gorillajs/mariadb
    expose: 
      - 3306
    volumes:
      - ../template:/root/templates
      - {{docker.data_path}}/{{project.domain}}/mysql:/var/lib/mysql
    entrypoint:
      - bin/sh
      - /root/templates/entrypoint-mariadb.sh
    container_name: mariadb.test

  web:
    # build: ./image
    # image: lamp.test
    image: gorillajs/wordpress
    ports:  
      - "{{docker.port}}:80"
    volumes:
      - ../template:/root/templates
      - ../../application:/var/www/{{project.domain}}/application
    entrypoint:
      - bin/sh
      - /root/templates/entrypoint-web-wordpress.sh
    container_name: {{project.domain}}

networks:
  default:
    external:
      name: gorillajs

