# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/mariadb . -f templates/common/dockerfile-alpine-mariadb

FROM gorillajs/alpine

MAINTAINER David Barreiros Ibáñez <hola@davidbarreiros.es>

RUN adduser -u 1000 -D mysql \
    && apk add --no-cache mariadb mariadb-client \
    && rm -rf /var/cache/apk/*

COPY templates/common/mysql.cnf /etc/mysql/my.cnf 
