# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/python . -f templates/common/dockerfile-alpine-python

FROM gorillajs/alpine

MAINTAINER David Barreiros Ibáñez <hola@davidbarreiros.es>

RUN echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update && apk upgrade \
    && apk add --no-cache gcc musl-dev openrc \
    && apk add --no-cache python3 python3-dev py3-pip py3-psycopg2 \
    && pip3 install --upgrade pip setuptools \
    && rm -rf /var/cache/apk/*
