# Esta imagen sirve como base para el ejemplo de "Hazolo tú mismo" de gorillajs.com
# docker build -t gorillajs/php7 . -f templates/common/dockerfile-alpine-php7

FROM gorillajs/alpine

MAINTAINER David Barreiros Ibáñez <hola@davidbarreiros.es>

RUN echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update && apk upgrade \
    && mkdir -p /run/apache2 \
    && apk add --no-cache apache2 apache2-utils \
    && apk add --no-cache php7 php7-zlib php7-phar php7-apache2 php7-mysqli php7-curl php7-openssl php7-json php7-iconv php7-session \
    && apk add --no-cache mysql-client \
    && apk add --no-cache openrc \
    && rm -rf /var/cache/apk/*

CMD apachectl start -D FOREGROUND


