# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/tools . -f templates/common/dockerfile-alpine-tools

FROM gorillajs/alpine

MAINTAINER David Barreiros Ibáñez <hola@davidbarreiros.es>

RUN echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update && apk upgrade \
    && apk add python py-pip groff less git \
    # && pip install --upgrade --user "awscli<=1.10.0" \
    # && apk --purge -v del py-pip \
    && pip install --upgrade --user boto3 \
    && apk add duplicity \
	&& rm /var/cache/apk/* \
    && echo "alias aws='./root/.local/bin/aws'" >> /etc/profile.d/aliases.sh


