# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/alpine . -f dockerfiles/dockerfile-alpine

FROM alpine

MAINTAINER David Barreiros Ibáñez <hola@davidbarreiros.es>

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update && apk upgrade \
    && apk add curl wget git \
    && apk add inotify-tools \
    && apk add shadow \
    && rm -rf /var/cache/apk/* 
