# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/wordpress . -f dockerfiles/dockerfile-alpine-wordpress

FROM gorillajs/lamp

MAINTAINER David Barreiros Ibáñez <hola@davidbarreiros.es>

RUN apk update && apk upgrade \
    && apk add --no-cache php7-dom php7-mbstring php7-xml php7-simplexml php7-ctype \
    && apk add --no-cache unison \
    && curl -o /usr/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x /usr/bin/wp \
    && rm -rf /var/cache/apk/*
