mysql:
  image: gorillajs/mysql
  expose: 
    - 3306
  volumes:
    - ../{{docker.templatefolder}}:/root/templates
    - ../../{{project.datafolder}}:/var/lib/mysql
web:
  image: gorillajs/apache-base
  ports:  
    - "{{docker.port}}:80"
  volumes:
    - ../{{docker.templatefolder}}:/root/templates
    - ../../{{project.srcout}}:/var/www/{{project.domain}}/{{project.srcout}}
  links:
    - mysql:mysql
  expose: 
    - {{docker.port}}
  container_name: {{project.slug}}

