FROM ubuntu

RUN echo "deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs) main restricted multiverse\ndeb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main restricted multiverse" | sudo tee -a /etc/apt/sources.list > /dev/null
RUN apt-get update
RUN apt-get -y install apache2-mpm-prefork apache2-mpm-worker libapache2-mod-fastcgi php5-fpm php5-mysqlnd php5-memcached memcached php-apc supervisor

COPY templates/wordpress/apache-supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN sed -i 's/;pm.start_servers/pm.start_servers/g' /etc/php5/fpm/pool.d/www.conf
RUN echo "fs.file-max = 10240" >> /etc/sysctl.conf 
RUN echo "* soft nofile 10240 \n* hard nofile 10240 \n* soft nproc 10240 \n* hard nproc 10240" > /etc/security/limits.conf
RUN echo "Include httpd.conf" >> /etc/apache2/apache2.conf
RUN a2dismod mpm_event && a2enmod rewrite && a2enmod mpm_prefork && a2enmod actions fastcgi alias

CMD ["/usr/bin/supervisord"]
