# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/python-base . -f templates/common/dockerfile-python

FROM gorillajs/ubuntu

RUN apt-get update \
        && apt-get -y install python-pip libpq-dev python-dev apache2 libapache2-mod-wsgi libgcrypt11-dev zlib1g-dev libssl-dev supervisor  \
        && apt-get autoremove

COPY templates/common/python-supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
