FROM ubuntu:14.04

RUN apt-get update
RUN apt-get -y install mysql-server supervisor

COPY templates/wordpress/mysql-supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
