# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/mysql . -f templates/common/dockerfile-mysql

FROM ubuntu:14.04

RUN apt-get update && apt-get -y install mysql-server supervisor mytop man-db && apt-get autoremove

COPY templates/common/mysql-supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
