# Este archivo se tiene que ejecutar desde la raíz de GorillaJS.
# docker build -t gorillajs/apache-base . -f templates/common/dockerfile-apache

FROM ubuntu:14.04

RUN echo "deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs) main restricted multiverse\ndeb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main restricted multiverse" | sudo tee -a /etc/apt/sources.list > /dev/null \ 
    && apt-get update && apt-get -y --fix-missing install apache2-mpm-prefork apache2-mpm-worker libapache2-mod-php5 libapache2-mod-fastcgi libapache2-mod-evasive php5-fpm php5-memcache php5-memcached memcached php-apc php5-mysql php5-mcrypt supervisor php5-curl curl wget git && export DEBIAN_FRONTEND=noninteractive && apt-get -q -y install phpmyadmin apt-transport-https \
    && curl https://repo.varnish-cache.org/ubuntu/GPG-key.txt | apt-key add - && echo "deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-4.0" >> /etc/apt/sources.list.d/varnish-cache.list && apt-get update && apt-get -y install varnish \
    && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY templates/common/apache-supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY templates/common/apache-httpd.conf /etc/apache2/httpd.conf
COPY templates/common/config.inc.php /etc/phpmyadmin/config.inc.php
COPY templates/common/php-php5-fpm.conf /etc/apache2/conf-available/php5-fpm.conf
COPY templates/common/devicedetect.vcl /etc/varnish/devicedetect.vcl

RUN sed -i 's/;pm.start_servers/pm.start_servers/g' /etc/php5/fpm/pool.d/www.conf \
    && git clone https://github.com/Neilpang/acme.sh.git \
    && echo "fs.file-max = 10240" >> /etc/sysctl.conf \
    && echo "* soft nofile 10240 \n* hard nofile 10240 \n* soft nproc 10240 \n* hard nproc 10240" > /etc/security/limits.conf \
    && echo "Include httpd.conf" >> /etc/apache2/apache2.conf \
    && touch /etc/apache2/httpd.conf \
    && a2dismod mpm_event && a2enmod rewrite && a2enmod mpm_prefork && a2enmod actions fastcgi alias && a2enmod php5 && php5enmod mcrypt \
    && apt-get autoremove

CMD ["/usr/bin/supervisord"]
