version: '3'

services:

  mysql:
    image: gorillajs/mysql
    expose: 
      - 3306
    volumes:
      - ../{{docker.templatefolder}}:/root/templates
      - ../../data:/var/lib/mysql

  web:
    image: gorillajs/apache-base
    ports:  
      - "{{docker.port}}:80"
    volumes:
      - ../{{docker.templatefolder}}:/root/templates
      - ../../src:/var/www/{{project.domain}}/src
    container_name: {{project.domain}}

networks:
  default:
    external:
      name: gorillajs

